apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: payment-image
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/payment
    newTag: v1.0.0

configMapGenerator:
  - name: payment-config
    namespace: apps
    literals:
      - CLOUD_PROVIDER=aws
      - SERVICE_NAME=payment

patches:
  - path: serviceaccount-patch.yaml
