apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: inventory-image
    newName: europe-west1-docker.pkg.dev/PROJECT_ID/apps/inventory
    newTag: v1.0.0

configMapGenerator:
  - name: inventory-config
    namespace: apps
    literals:
      - CLOUD_PROVIDER=gcp
      - SERVICE_NAME=inventory

patches:
  - path: serviceaccount-patch.yaml
