apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - projects/apps-project.yaml
  - applications/platform-gcp.yaml
  - applications/platform-aws.yaml
  - applications/platform-azure.yaml
  - applicationsets/services-gcp.yaml
  - applicationsets/services-aws.yaml
  - applicationsets/services-azure.yaml
