apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: user
  ports:
    - name: http
      port: 80
      targetPort: http
