apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gcp
  namespace: argocd
spec:
  project: apps

  source:
    repoURL: https://github.com/Snuffules/cloud_agnostic_microservices.git
    targetRevision: main
    path: k8s/platform

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
