apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: payment-allow-checkout
  namespace: apps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/apps/sa/checkout
