apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment
  ports:
    - name: http
      port: 80
      targetPort: http
