apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/apps.yaml
  - ingress/gateway.yaml
  - ingress/checkout-virtualservice.yaml
  - ingress/user-virtualservice.yaml
  - istio-policies/peer-authentication-strict.yaml
